[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:get_id()'''
position = "after"
payload = '''
if next(find_joker("j_jam_double_vision")) then
    return 2
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:is_face(from_boss)'''
position = "after"
payload = '''
if next(find_joker("j_jam_prosopagnosia")) then
    return false
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''if hand_chips*mult > 0 then'''
position = "before"
payload = '''
G.GAME.round_resets.jam_last_chips = math.floor(hand_chips*mult)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''if G.GAME.blind.name == 'The Serpent' and'''
position = "before"
payload = '''
local jam_pot_extra = 0
for _, j in ipairs(find_joker("j_jam_greedy_pot")) do
    jam_pot_extra = jam_pot_extra + j.ability.extra
end
if jam_pot_extra and G.GAME.current_round.hands_played > 0 or G.GAME.current_round.discards_used > 0 then
    hand_space = math.min(#G.deck.cards, hand_space + jam_pot_extra)
end
'''
match_indent = true
