[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]] # Double Vision, make cards 2's
[patches.pattern]
target = "card.lua"
pattern = '''function Card:get_id()'''
position = "after"
payload = '''
if next(SMODS.find_card("j_jam_double_vision")) then
    return 2
end
'''
match_indent = true

[[patches]] # Prosopagnosia make cards not faces
[patches.pattern]
target = "card.lua"
pattern = '''function Card:is_face(from_boss)'''
position = "after"
payload = '''
if next(SMODS.find_card("j_jam_prosopagnosia")) then
    return false
end
'''
match_indent = true

[[patches]] # Store the last scored chips, used for one more time and scouter
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''if hand_chips*mult > 0 then'''
position = "before"
payload = '''
G.GAME.round_resets.jam_last_chips = math.floor(hand_chips*mult)
'''
match_indent = true

[[patches]] # Greedy Pot extra cards
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''if G.GAME.blind.name == 'The Serpent' and'''
position = "before"
payload = '''
local jam_pot_extra = 0
for _, j in ipairs(SMODS.find_card("j_jam_greedy_pot")) do
    jam_pot_extra = jam_pot_extra + j.ability.extra
end
if jam_pot_extra and G.GAME.current_round.hands_played > 0 or G.GAME.current_round.discards_used > 0 then
    hand_space = math.min(#G.deck.cards, hand_space + jam_pot_extra)
end
'''
match_indent = true

[[patches]] # Scouter sell when about to lose
[patches.pattern]
target = "game.lua"
pattern = '''G.STATE = G.STATES.NEW_ROUND'''
position = "after"
payload = '''
local scouters = SMODS.find_card("j_jam_scouter")
if G.GAME.current_round.hands_left < 1 and next(scouters) then
    G.STATE = G.STATES.DRAW_TO_HAND
    scouters[1]:sell_card()
end
'''
match_indent = true

[[patches]] # Make the play button work with more than 5 cards selected (Pierrot)
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''if #G.hand.highlighted <= 0 or G.GAME.blind.block_play or #G.hand.highlighted > 5 then'''
position = "at"
payload = '''
if #G.hand.highlighted <= 0 or G.GAME.blind.block_play or #G.hand.highlighted > G.hand.config.highlighted_limit then
'''
match_indent = true

[[patches]] # Safari joker all suits
[patches.pattern]
target = "card.lua"
pattern = '''if flush_calc then'''
position = "before"
payload = '''
if next(SMODS.find_card("j_jam_safari")) and (not self.debuff or bypass_debuff) then
    return true
end
'''
match_indent = true

[[patches]] # Greener pastures created card sell cost
[patches.pattern]
target = "card.lua"
pattern = '''if self.area and self.ability.couponed and (self.area == G.shop_jokers or self.area == G.shop_booster) then self.cost = 0 end'''
position = "after"
payload = '''
if self.ability and self.ability.jam_greener_pastures then
    self.cost = 0
    self.sell_cost = 0
end'''
match_indent = true

[[patches]] # Greener pastures spawned card hover tooltip
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if _c.set == 'Other' then'''
position = "before"
payload = '''
if card and card.ability and card.ability.jam_greener_pastures then
    info_queue[#info_queue + 1] = {
        key = 'jam_greener_pastures_note', 
        set = 'Other'
    }
end'''
match_indent = true

[[patches]] # Greener pastures card destroyed
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''G.jokers.cards[i]:calculate_joker({setting_blind = true, blind = G.GAME.round_resets.blind})'''
position = "after"
payload = '''
do
    local card = G.jokers.cards[i]
    if card and card.ability and card.ability.jam_greener_pastures then
        card:start_dissolve()
    end
end'''
match_indent = true

[[patches]] # Greener pastures card copied (remove greener pastures effect) 
[patches.pattern]
target = "card.lua"
pattern = '''if not self.added_to_deck then'''
position = "after"
payload = '''
if not from_debuff and self.ability.jam_greener_pastures then
    self.ability.jam_greener_pastures = nil
    self:set_cost()
end
'''
match_indent = true
